### ISSUE TITLE
Generates warnings when used by extension/framework

### ISSUE THREAD

**Issue by brindy** [gumob/PunycodeSwift#2]
Hi,

Thanks for this project, very useful. 

There's a slight problem in that it generates a warning when used in a project with extensions or frameworks:

```:-1: linking against a dylib which is not safe for use in application extensions: /Users/brindy/Projects/DuckDuckGo/iOS/Carthage/Build/iOS/Punycode.framework/Punycode```

The solution is to check the "Allow app extension API only" on the target for iOS.

I can submit a PR for this once time allows.

**Comment by gumob** [comment]
Hi,

Thank you for fixing the warning.
Please send a PR. I will merge as soon as I can confirm.

**Comment by brindy** [comment]
Fixed by #3

**Comment by gumob** [comment]
Thank you for the fix. I have merged the PR.
